### ISSUE TITLE
Support for ICU 75.1

### ISSUE THREAD

**Issue by stof** [shivammathur/icu-intl#8]
**Describe the feature**
It would be great to have support for builds using ICU 75.1

**Version**
- [x] I have checked that the feature is missing in the latest version.

**Underlying issue**

**Describe alternatives**

**Additional context**
Looking at the commit history, it seems like the work has been started already. However, the jobs building the 75.1 ICU version have failed for PHP 7: https://github.com/shivammathur/icu-intl/actions/runs/10023485108/job/27704440277
And the readme does not list ICU 75.1 as supported for any PHP versions.

Symfony rely on this in their CI job. See https://github.com/symfony/symfony/pull/58183 for a discussion about updating to ICU 75.1 there.

**Are you willing to submit a PR?**

**Comment by shivammathur** [comment]
@stof 
I have added support for 75.1, it should work now.
